routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/{id}', 'UserController@show')->name('show');
    Route::get('/{id}/comment', 'UserController@comment')->name('comment');
    Route::post('/{id}/store-comment', 'UserController@commentStore')->name('store-comment');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'comment'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Redirect;

class UserController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $title = 'User Card - ' . $user->name;

        return view('user.view', compact('title', 'user'));
    }

    public function comment($id)
    {
        $user = User::findOrFail($id);
        $title = 'User Card - ' . $user->name . ' - Comment';

        return view('user.comment', compact('title', 'user'));
    }

    public function commentStore($id, Request $request)
    {
        $user = User::findOrFail($id);

        $rules = [
            'comment' => 'required',
            'password' => ['required', function ($attribute, $value, $fail) use ($user) {
                if (!\Hash::check($value, $user->password)) {
                    return $fail(__('The password is incorrect.'));
                }
            }]
        ];
        $messages = [
            'unique' => 'Username already exists. Please choose a different username.',
        ];

        $this->validate($request, $rules, $messages);

        $user->comment = ($user->comment != '' ? $user->comment . '<br>' : '') . $request->comment;
        $user->save();

        return Redirect::route('user.comment',)->with('message', 'User Comment Successfully Added!');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE HTML>
<html>
<head>
    <title>@yield('title', 'Laravel')</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{{asset('assets/css/main.css')}}" />
    <noscript>
        <link rel="stylesheet" href="{{asset('assets/css/noscript.css')}}" />
    </noscript>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body class="is-preload">
    <div id="wrapper">
        @yield('content')

        <footer id="footer">
            <ul class="copyright">
                <li>&copy; Pictureworks</li>
            </ul>
        </footer>
    </div>

    <script>
        if ('addEventListener' in window) {
            window.addEventListener('load', function() { document.body.className = document.body.className.replace(/\bis-preload\b/, ''); });
            document.body.className += (navigator.userAgent.match(/(MSIE|rv:11\.0)/) ? ' is-ie' : '');
        }
    </script>
</body>
</html>

resources/views/user/comment.blade.php
@extends('layouts.app')

@section('title', $title)

@section('content')
    <section id="main">
        <header class="text-left">
            @if ($errors->any())
                <div class="alert alert-danger" style="text-transform:none !important">
                    @foreach ($errors->all() as $error)
                        {{ $error }}
                    @endforeach
                </div>
            @endif

            @if(session()->has('message'))
                <div class="alert alert-success" style="text-transform:none !important">
                    {{ session()->get('message') }}
                </div>
            @endif

            <form action="{{route('user.store-comment', $user->id)}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" style="text-transform:none !important" required>
                </div>
                <div class="form-group">
                    <label for="comment">Comment:</label>
                    <textarea class="form-control" rows="5" id="comment" name="comment" style="text-transform:none !important" required></textarea>
                </div>
                @if($user->comment != '')
                    <div class="form-group" style="text-transform:none !important">
                        <label>Existing Comment:</label>
                        <p>
                            {!!nl2br($user->comment)!!}
                        </p>
                    </div>
                @endif
                <div class="form-group text-center">
                    <a href="{{route('user.show', $user->id)}}" class="btn btn-default">Back</a>
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </form>
        </header>
    </section>
@endsection

resources/views/user/view.blade.php
@extends('layouts.app')

@section('title', $title)

@section('content')
    <section id="main">
        <header>
            <span class="avatar"><img src="{{asset('assets/images/users/'. $user->id .'.jpg')}}" alt="" /></span>
            <h1 style="font-size:2em !important;">{{$user->name}}</h1>
            <p style="text-transform:none !important">
                {!!nl2br($user->comment)!!}
            </p>
            <a href="{{route('user.comment', $user->id)}}" class="btn btn-default">Add Comment</a>
        </header>
    </section>
@endsection